stages:
  - sonarqube_stage
sonarqube_ci:
  image: 172.27.5.95:5000/sonarsource/sonar-scanner-cli:latest
  stage: sonarqube_stage
  variables:
    SONAR_PROJECT_BASE_DIR: "$CI_PROJECT_DIR"
  script:
    - /usr/bin/entrypoint.sh sonar-scanner -Dsonar.projectKey="$CI_PROJECT_NAME"
  tags:
    - digimi
